### ISSUE TITLE
Wrong answer for test case:

### ISSUE THREAD

**Issue by jfsanin** [omaryasser/UVA#1]
Hi, I know you already get accept in UVA however there is a test case (in fact, there are a lot) where you code fails:

1

4 3

2 1 2 3 4
<
2 1 3 2 4
<
2 2 3 1 4
<

the output should be 4 but your output is 0.

**Comment by omaryasser** [comment]
Which problem?  :D

**Comment by jfsanin** [comment]
665 - False coin.

**Comment by omaryasser** [comment]
nice one :D ty :D
